### ISSUE TITLE
Join error with phoenix 1.3

### ISSUE THREAD

**Issue by rlb3** [fbonetti/elm-phoenix-socket#30]
elm: 0.18
elm-phoenix-socket: 2.2.0
phoenix: 1.3.0

I can connect to the phoenix channel from elm but when I try to join a channel I get a phoenix error:

```
[error] Ranch protocol #PID<0.833.0> (:cowboy_protocol) of listener PushTimeWeb.Endpoint.HTTP terminated
** (exit) exited in: Phoenix.Endpoint.CowboyWebSocket.resume()
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: %{"event" => "phx_join", "payload" => %{}, "ref" => 0, "topic" => "time:lobby"}
            (phoenix) lib/phoenix/transports/v2/websocket_serializer.ex:34: Phoenix.Transports.V2.WebSocketSerializer.decode!/2
            (phoenix) lib/phoenix/transports/websocket.ex:121: Phoenix.Transports.WebSocket.ws_handle/3
            (phoenix) lib/phoenix/endpoint/cowboy_websocket.ex:77: Phoenix.Endpoint.CowboyWebSocket.websocket_handle/3
            (cowboy) /Users/robert/Projects/push_time/deps/cowboy/src/cowboy_websocket.erl:588: :cowboy_websocket.handler_call/7
            (phoenix) lib/phoenix/endpoint/cowboy_websocket.ex:49: Phoenix.Endpoint.CowboyWebSocket.resume/3
            (cowboy) /Users/robert/Projects/push_time/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

The channel join part of my update looks like this:

```elm
        JoinChannel ->
            let
                channel =
                    Phoenix.Channel.init "time:lobby"
                        |> Phoenix.Channel.onJoinError JoinFail
                        |> Phoenix.Channel.onError JoinFail
                        |> Phoenix.Channel.onJoin JoinFail

                _ =
                    Debug.log "channel" channel

                ( phxSocket, phxCmd ) =
                    Phoenix.Socket.join channel model.phxSocket

                _ =
                    Debug.log "socket" phxSocket
            in
                ( { model | phxSocket = phxSocket }
                , Cmd.map PhoenixMsg phxCmd
                )
```

I'm not sure if I'm doing something wrong but as far as I can tell I'm doing what I should.

**Comment by maxstr** [comment]
Would need to see the Elixir side, but I'm guessing you don't have a matching channel route.

**Comment by rlb3** [comment]
This is what I have in `user_socket.ex`

```elixir
channel "time:lobby", PushTimeWeb.TimeChannel
```

This is all in have in PushTimeWeb.TimeChannel for the join function:

```elixir
  def join("time:lobby", payload, socket) do
    {:ok, socket}
  end
```

Update: I just tried it with the phoenix `socket.js` and it worked as expected.

**Comment by rlb3** [comment]
I created a new project and copied the code over and it works as intended. There must be something wrong in my original project.
